### ISSUE TITLE
RedisDB port issue

### ISSUE THREAD

**Issue by slee172** [CancerDataScience/HistomicsML-TA#67]
I did that but it is still throwing an error

```
Traceback (most recent call last):
  File "run_model_server.py", line 1153, in <module>
    run()
  File "run_model_server.py", line 74, in run
    queue = db.lrange(set.REQUEST_QUEUE, set.REQUEST_START, set.REQUEST_END)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1975, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 898, in execute_comm
and
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 1192, in get_con
nection
    connection.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to localhost:8880:6379. Name or service not known.
```

_Originally posted by @Reasat in https://github.com/CancerDataScience/HistomicsML2/issues/66#issuecomment-724982446_

**Comment by slee172** [comment]
@Reasat Oh, this is not a trivial issue because RedisDB uses its own port (but you are trying to use 8880 port). I think the best way you can do is changing from "localhost:8880" to "localhost" in "settings.py", and then use your port to 80 instead of 8880. HistomicsML uses "localhost" as a parameter in the front-end program and sends it to the back-end program. So, if we modify the port, it could affect both the front-end and the back-end programs.
From my experience, one solution to this issue is to stop your current 80 port and use it for HistomicsML.
